/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_bsdiff_BsdiffUtil */

#ifndef _Included_com_demo_bsdiff_BsdiffUtil
#define _Included_com_demo_bsdiff_BsdiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_bsdiff_BsdiffUtil
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demo_bsdiff_BsdiffUtil_bspatch
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
